//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATextremePrepLU
    {
        public lkpSWATextremePrepLU()
        {
            this.tblSWATWAriskPreps = new HashSet<tblSWATWAriskPrep>();
            this.tblSWATWAriskPreps1 = new HashSet<tblSWATWAriskPrep>();
            this.tblSWATWAriskPreps2 = new HashSet<tblSWATWAriskPrep>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATWAriskPrep> tblSWATWAriskPreps { get; set; }
        public virtual ICollection<tblSWATWAriskPrep> tblSWATWAriskPreps1 { get; set; }
        public virtual ICollection<tblSWATWAriskPrep> tblSWATWAriskPreps2 { get; set; }
    }
}
