//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWAThhCleanLU
    {
        public lkpSWAThhCleanLU()
        {
            this.tblSWATSFcentrals = new HashSet<tblSWATSFcentral>();
            this.tblSWATSFlats = new HashSet<tblSWATSFlat>();
            this.tblSWATSFseptics = new HashSet<tblSWATSFseptic>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATSFcentral> tblSWATSFcentrals { get; set; }
        public virtual ICollection<tblSWATSFlat> tblSWATSFlats { get; set; }
        public virtual ICollection<tblSWATSFseptic> tblSWATSFseptics { get; set; }
    }
}
