//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWAT5rankLU
    {
        public lkpSWAT5rankLU()
        {
            this.tblSWATCCschools = new HashSet<tblSWATCCschool>();
            this.tblSWATCCsocials = new HashSet<tblSWATCCsocial>();
            this.tblSWATCCsocials1 = new HashSet<tblSWATCCsocial>();
            this.tblSWATCCwaterManagements = new HashSet<tblSWATCCwaterManagement>();
            this.tblSWATCCwaterManagements1 = new HashSet<tblSWATCCwaterManagement>();
            this.tblSWATCCwaterManagements2 = new HashSet<tblSWATCCwaterManagement>();
            this.tblSWATCCwaterManagements3 = new HashSet<tblSWATCCwaterManagement>();
            this.tblSWATCCwaterManagements4 = new HashSet<tblSWATCCwaterManagement>();
            this.tblSWATSWPags = new HashSet<tblSWATSWPag>();
            this.tblSWATSWPags1 = new HashSet<tblSWATSWPag>();
            this.tblSWATSWPdevs = new HashSet<tblSWATSWPdev>();
            this.tblSWATHPPcoms = new HashSet<tblSWATHPPcom>();
            this.tblSWATSWPls = new HashSet<tblSWATSWPl>();
            this.tblSWATHPPkhps = new HashSet<tblSWATHPPkhp>();
            this.tblSWATSFcentrals = new HashSet<tblSWATSFcentral>();
            this.tblSWATSFseptics = new HashSet<tblSWATSFseptic>();
            this.tblSWATSFseptics1 = new HashSet<tblSWATSFseptic>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATCCschool> tblSWATCCschools { get; set; }
        public virtual ICollection<tblSWATCCsocial> tblSWATCCsocials { get; set; }
        public virtual ICollection<tblSWATCCsocial> tblSWATCCsocials1 { get; set; }
        public virtual ICollection<tblSWATCCwaterManagement> tblSWATCCwaterManagements { get; set; }
        public virtual ICollection<tblSWATCCwaterManagement> tblSWATCCwaterManagements1 { get; set; }
        public virtual ICollection<tblSWATCCwaterManagement> tblSWATCCwaterManagements2 { get; set; }
        public virtual ICollection<tblSWATCCwaterManagement> tblSWATCCwaterManagements3 { get; set; }
        public virtual ICollection<tblSWATCCwaterManagement> tblSWATCCwaterManagements4 { get; set; }
        public virtual ICollection<tblSWATSWPag> tblSWATSWPags { get; set; }
        public virtual ICollection<tblSWATSWPag> tblSWATSWPags1 { get; set; }
        public virtual ICollection<tblSWATSWPdev> tblSWATSWPdevs { get; set; }
        public virtual ICollection<tblSWATHPPcom> tblSWATHPPcoms { get; set; }
        public virtual ICollection<tblSWATSWPl> tblSWATSWPls { get; set; }
        public virtual ICollection<tblSWATHPPkhp> tblSWATHPPkhps { get; set; }
        public virtual ICollection<tblSWATSFcentral> tblSWATSFcentrals { get; set; }
        public virtual ICollection<tblSWATSFseptic> tblSWATSFseptics { get; set; }
        public virtual ICollection<tblSWATSFseptic> tblSWATSFseptics1 { get; set; }
    }
}
