//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATSectionLU
    {
        public lkpSWATSectionLU()
        {
            this.lkpSWATScoreVarsLUs = new HashSet<lkpSWATScoreVarsLU>();
            this.lkpSWATScoreVarsLUs1 = new HashSet<lkpSWATScoreVarsLU>();
        }
    
        public int ID { get; set; }
        public string SectionName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<lkpSWATScoreVarsLU> lkpSWATScoreVarsLUs { get; set; }
        public virtual ICollection<lkpSWATScoreVarsLU> lkpSWATScoreVarsLUs1 { get; set; }
    }
}
