//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATextremeEventsLU
    {
        public lkpSWATextremeEventsLU()
        {
            this.tblSWATWAextremeEvents = new HashSet<tblSWATWAextremeEvent>();
            this.tblSWATWAextremeEvents1 = new HashSet<tblSWATWAextremeEvent>();
            this.tblSWATWAextremeEvents2 = new HashSet<tblSWATWAextremeEvent>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATWAextremeEvent> tblSWATWAextremeEvents { get; set; }
        public virtual ICollection<tblSWATWAextremeEvent> tblSWATWAextremeEvents1 { get; set; }
        public virtual ICollection<tblSWATWAextremeEvent> tblSWATWAextremeEvents2 { get; set; }
    }
}
