//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATWPsectionLU
    {
        public lkpSWATWPsectionLU()
        {
            this.lkpSWATWPscoreLUs = new HashSet<lkpSWATWPscoreLU>();
        }
    
        public int ID { get; set; }
        public string SectionName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<lkpSWATWPscoreLU> lkpSWATWPscoreLUs { get; set; }
    }
}
