//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATWPscoreLU
    {
        public lkpSWATWPscoreLU()
        {
            this.tblSWATWPscores = new HashSet<tblSWATWPscore>();
        }
    
        public int ID { get; set; }
        public string ScoreName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SectionID { get; set; }
    
        public virtual lkpSWATWPsectionLU lkpSWATWPsectionLU { get; set; }
        public virtual ICollection<tblSWATWPscore> tblSWATWPscores { get; set; }
    }
}
