//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATScoreVarsLU
    {
        public lkpSWATScoreVarsLU()
        {
            this.tblSWATScores = new HashSet<tblSWATScore>();
            this.lkpSWATSectionLUs = new HashSet<lkpSWATSectionLU>();
        }
    
        public int ID { get; set; }
        public string VarName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SectionID { get; set; }
    
        public virtual ICollection<tblSWATScore> tblSWATScores { get; set; }
        public virtual ICollection<lkpSWATSectionLU> lkpSWATSectionLUs { get; set; }
        public virtual lkpSWATSectionLU lkpSWATSectionLU { get; set; }
    }
}
