//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSubnational
    {
        public lkpSubnational()
        {
            this.tblSWATLocations = new HashSet<tblSWATLocation>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public string Name { get; set; }
    
        public virtual lkpCountry lkpCountry { get; set; }
        public virtual ICollection<tblSWATLocation> tblSWATLocations { get; set; }
    }
}
