//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATwaterMonthLU
    {
        public lkpSWATwaterMonthLU()
        {
            this.tblSWATWAMonthlyQuantities = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities1 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities2 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities3 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities4 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities5 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities6 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities7 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities8 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities9 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities10 = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAMonthlyQuantities11 = new HashSet<tblSWATWAMonthlyQuantity>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities1 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities2 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities3 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities4 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities5 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities6 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities7 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities8 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities9 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities10 { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities11 { get; set; }
    }
}
