//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATgenderLU
    {
        public lkpSWATgenderLU()
        {
            this.tblSWATCCgenders = new HashSet<tblSWATCCgender>();
            this.tblSWATCCgenders1 = new HashSet<tblSWATCCgender>();
            this.tblSWATCCgenders2 = new HashSet<tblSWATCCgender>();
            this.tblSWATCCgenders3 = new HashSet<tblSWATCCgender>();
            this.tblSWATCCgenders4 = new HashSet<tblSWATCCgender>();
            this.tblSWATCCgenders5 = new HashSet<tblSWATCCgender>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATCCgender> tblSWATCCgenders { get; set; }
        public virtual ICollection<tblSWATCCgender> tblSWATCCgenders1 { get; set; }
        public virtual ICollection<tblSWATCCgender> tblSWATCCgenders2 { get; set; }
        public virtual ICollection<tblSWATCCgender> tblSWATCCgenders3 { get; set; }
        public virtual ICollection<tblSWATCCgender> tblSWATCCgenders4 { get; set; }
        public virtual ICollection<tblSWATCCgender> tblSWATCCgenders5 { get; set; }
    }
}
