//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATextVisitLU
    {
        public lkpSWATextVisitLU()
        {
            this.tblSWATCCexternalSupports = new HashSet<tblSWATCCexternalSupport>();
            this.tblSWATCCexternalSupports1 = new HashSet<tblSWATCCexternalSupport>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATCCexternalSupport> tblSWATCCexternalSupports { get; set; }
        public virtual ICollection<tblSWATCCexternalSupport> tblSWATCCexternalSupports1 { get; set; }
    }
}
