//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWAT5rankLU
    {
        public lkpSWAT5rankLU()
        {
            this.tblSWATCCschools = new HashSet<tblSWATCCschool>();
            this.tblSWATCCsocials = new HashSet<tblSWATCCsocial>();
            this.tblSWATCCsocials1 = new HashSet<tblSWATCCsocial>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATCCschool> tblSWATCCschools { get; set; }
        public virtual ICollection<tblSWATCCsocial> tblSWATCCsocials { get; set; }
        public virtual ICollection<tblSWATCCsocial> tblSWATCCsocials1 { get; set; }
    }
}
