//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpSWATwpaReliabilityMonthLU
    {
        public lkpSWATwpaReliabilityMonthLU()
        {
            this.tblSWATWPsupplies = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies1 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies2 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies3 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies4 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies5 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies6 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies7 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies8 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies9 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies10 = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPsupplies11 = new HashSet<tblSWATWPsupply>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> intorder { get; set; }
    
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies1 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies2 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies3 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies4 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies5 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies6 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies7 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies8 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies9 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies10 { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies11 { get; set; }
    }
}
