//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWATEntities : DbContext
    {
        public SWATEntities()
            : base("name=SWATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<lkpCountry> lkpCountries { get; set; }
        public DbSet<lkpRegion> lkpRegions { get; set; }
        public DbSet<lkpSubnational> lkpSubnationals { get; set; }
        public DbSet<tblSWATLocation> tblSWATLocations { get; set; }
        public DbSet<Userid> Userids { get; set; }
        public DbSet<tblSWATSurvey> tblSWATSurveys { get; set; }
    }
}
