//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATWAMonthlyQuantity
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> January { get; set; }
        public Nullable<int> February { get; set; }
        public Nullable<int> March { get; set; }
        public Nullable<int> April { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> June { get; set; }
        public Nullable<int> July { get; set; }
        public Nullable<int> August { get; set; }
        public Nullable<int> September { get; set; }
        public Nullable<int> October { get; set; }
        public Nullable<int> November { get; set; }
        public Nullable<int> December { get; set; }
    
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU1 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU2 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU3 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU4 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU5 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU6 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU7 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU8 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU9 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU10 { get; set; }
        public virtual lkpSWATwaterMonthLU lkpSWATwaterMonthLU11 { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
