//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATCCwaterManagement
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> watCom { get; set; }
        public string watAdminOther { get; set; }
        public Nullable<int> watActionPlan { get; set; }
        public Nullable<int> watRecords1 { get; set; }
        public Nullable<int> watRecords2 { get; set; }
        public Nullable<int> watRecords3 { get; set; }
        public Nullable<int> watRecords4 { get; set; }
        public Nullable<int> watRecords5 { get; set; }
        public Nullable<int> comSatisfaction { get; set; }
        public Nullable<int> watClassRep { get; set; }
        public Nullable<int> watComConcerns { get; set; }
        public Nullable<int> watTechStaff { get; set; }
        public Nullable<int> watTechTraining { get; set; }
        public Nullable<int> watBudget { get; set; }
        public bool watFinPlan1 { get; set; }
        public bool watFinPlan2 { get; set; }
        public Nullable<int> proPoor { get; set; }
    
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU { get; set; }
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU1 { get; set; }
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU2 { get; set; }
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU3 { get; set; }
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU4 { get; set; }
        public virtual lkpSWATcomSatisfactionLU lkpSWATcomSatisfactionLU { get; set; }
        public virtual lkpSWATproPoorLU lkpSWATproPoorLU { get; set; }
        public virtual lkpSWATwatActionPlanLU lkpSWATwatActionPlanLU { get; set; }
        public virtual lkpSWATwatBudgetLU lkpSWATwatBudgetLU { get; set; }
        public virtual lkpSWATwatClassRepLU lkpSWATwatClassRepLU { get; set; }
        public virtual lkpSWATwatComConcernsLU lkpSWATwatComConcernsLU { get; set; }
        public virtual lkpSWATwatComLU lkpSWATwatComLU { get; set; }
        public virtual lkpSWATwatTechStaffLU lkpSWATwatTechStaffLU { get; set; }
        public virtual lkpSWATwatTechTrainingLU lkpSWATwatTechTrainingLU { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
