//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATCCedu
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<double> eduPrim { get; set; }
        public Nullable<double> eduSec { get; set; }
        public Nullable<double> eduGradWomen { get; set; }
        public Nullable<double> eduGradMen { get; set; }
    
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
