//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATHPPcom
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> diarrhea { get; set; }
        public Nullable<int> survivorship { get; set; }
        public Nullable<int> medicalTime { get; set; }
        public Nullable<int> medicalCost { get; set; }
    
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU { get; set; }
        public virtual lkpSWATmedicalCostLU lkpSWATmedicalCostLU { get; set; }
        public virtual lkpSWATmedicalTimeLU lkpSWATmedicalTimeLU { get; set; }
        public virtual lkpSWATsurvivorshipLU lkpSWATsurvivorshipLU { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
