//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATSurvey
    {
        public tblSWATSurvey()
        {
            this.tblSWATBackgroundinfoes = new HashSet<tblSWATBackgroundinfo>();
            this.tblSWATCCedus = new HashSet<tblSWATCCedu>();
            this.tblSWATCCindigs = new HashSet<tblSWATCCindig>();
            this.tblSWATCCschools = new HashSet<tblSWATCCschool>();
            this.tblSWATCCtrains = new HashSet<tblSWATCCtrain>();
            this.tblSWATWAannualPrecips = new HashSet<tblSWATWAannualPrecip>();
            this.tblSWATWAclimateChanges = new HashSet<tblSWATWAclimateChange>();
            this.tblSWATWAextremeEvents = new HashSet<tblSWATWAextremeEvent>();
            this.tblSWATWAgroundWaters = new HashSet<tblSWATWAgroundWater>();
            this.tblSWATWAMonthlyQuantities = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAPrecipitations = new HashSet<tblSWATWAPrecipitation>();
            this.tblSWATWAriskPreps = new HashSet<tblSWATWAriskPrep>();
            this.tblSWATWAsurfaceWaters = new HashSet<tblSWATWAsurfaceWater>();
            this.tblSWATCCfinancials = new HashSet<tblSWATCCfinancial>();
            this.tblSWATCCgenders = new HashSet<tblSWATCCgender>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int LocationID { get; set; }
    
        public virtual ICollection<tblSWATBackgroundinfo> tblSWATBackgroundinfoes { get; set; }
        public virtual ICollection<tblSWATCCedu> tblSWATCCedus { get; set; }
        public virtual ICollection<tblSWATCCindig> tblSWATCCindigs { get; set; }
        public virtual ICollection<tblSWATCCschool> tblSWATCCschools { get; set; }
        public virtual ICollection<tblSWATCCtrain> tblSWATCCtrains { get; set; }
        public virtual tblSWATLocation tblSWATLocation { get; set; }
        public virtual Userid Userid1 { get; set; }
        public virtual ICollection<tblSWATWAannualPrecip> tblSWATWAannualPrecips { get; set; }
        public virtual ICollection<tblSWATWAclimateChange> tblSWATWAclimateChanges { get; set; }
        public virtual ICollection<tblSWATWAextremeEvent> tblSWATWAextremeEvents { get; set; }
        public virtual ICollection<tblSWATWAgroundWater> tblSWATWAgroundWaters { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities { get; set; }
        public virtual ICollection<tblSWATWAPrecipitation> tblSWATWAPrecipitations { get; set; }
        public virtual ICollection<tblSWATWAriskPrep> tblSWATWAriskPreps { get; set; }
        public virtual ICollection<tblSWATWAsurfaceWater> tblSWATWAsurfaceWaters { get; set; }
        public virtual ICollection<tblSWATCCfinancial> tblSWATCCfinancials { get; set; }
        public virtual ICollection<tblSWATCCgender> tblSWATCCgenders { get; set; }
    }
}
