//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATWAriskPrep
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> riskFire { get; set; }
        public Nullable<int> riskFlood { get; set; }
        public Nullable<int> riskDrought { get; set; }
        public Nullable<int> prepFire { get; set; }
        public Nullable<int> prepFlood { get; set; }
        public Nullable<int> prepDrought { get; set; }
    
        public virtual lkpSWATextremePrepLU lkpSWATextremePrepLU { get; set; }
        public virtual lkpSWATextremePrepLU lkpSWATextremePrepLU1 { get; set; }
        public virtual lkpSWATextremePrepLU lkpSWATextremePrepLU2 { get; set; }
        public virtual lkpSWATextremeRiskLU lkpSWATextremeRiskLU { get; set; }
        public virtual lkpSWATextremeRiskLU lkpSWATextremeRiskLU1 { get; set; }
        public virtual lkpSWATextremeRiskLU lkpSWATextremeRiskLU2 { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
