//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATWPoverview
    {
        public tblSWATWPoverview()
        {
            this.tblSWATWPscores = new HashSet<tblSWATWPscore>();
            this.tblSWATWPsupplies = new HashSet<tblSWATWPsupply>();
            this.tblSWATWPqualities = new HashSet<tblSWATWPquality>();
        }
    
        public long ID { get; set; }
        public int SurveyID { get; set; }
        public string wpname { get; set; }
        public Nullable<int> wpaLoc { get; set; }
        public bool wpaUseDom { get; set; }
        public bool wpaUseInst { get; set; }
        public bool wpaUseEc { get; set; }
        public string wpaType { get; set; }
    
        public virtual lkpSWATwpaLoc lkpSWATwpaLoc { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
        public virtual ICollection<tblSWATWPscore> tblSWATWPscores { get; set; }
        public virtual ICollection<tblSWATWPsupply> tblSWATWPsupplies { get; set; }
        public virtual ICollection<tblSWATWPquality> tblSWATWPqualities { get; set; }
    }
}
