//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATWAPrecipitation
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<double> January { get; set; }
        public Nullable<double> February { get; set; }
        public Nullable<double> March { get; set; }
        public Nullable<double> April { get; set; }
        public Nullable<double> May { get; set; }
        public Nullable<double> June { get; set; }
        public Nullable<double> July { get; set; }
        public Nullable<double> August { get; set; }
        public Nullable<double> September { get; set; }
        public Nullable<double> October { get; set; }
        public Nullable<double> November { get; set; }
        public Nullable<double> December { get; set; }
    
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
