//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATWPoverview
    {
        public long ID { get; set; }
        public int SurveyID { get; set; }
        public string wpname { get; set; }
        public Nullable<int> wpaLoc { get; set; }
        public bool wpaUseDom { get; set; }
        public bool wpaUseInst { get; set; }
        public bool wpaUseEc { get; set; }
    
        public virtual lkpSWATwpaLoc lkpSWATwpaLoc { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
