//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATSurvey
    {
        public tblSWATSurvey()
        {
            this.tblSWATBackgroundinfoes = new HashSet<tblSWATBackgroundinfo>();
            this.tblSWATWAPrecipitations = new HashSet<tblSWATWAPrecipitation>();
            this.tblSWATWAMonthlyQuantities = new HashSet<tblSWATWAMonthlyQuantity>();
            this.tblSWATWAannualPrecips = new HashSet<tblSWATWAannualPrecip>();
            this.tblSWATWAclimateChanges = new HashSet<tblSWATWAclimateChange>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int LocationID { get; set; }
    
        public virtual ICollection<tblSWATBackgroundinfo> tblSWATBackgroundinfoes { get; set; }
        public virtual tblSWATLocation tblSWATLocation { get; set; }
        public virtual Userid Userid1 { get; set; }
        public virtual ICollection<tblSWATWAPrecipitation> tblSWATWAPrecipitations { get; set; }
        public virtual ICollection<tblSWATWAMonthlyQuantity> tblSWATWAMonthlyQuantities { get; set; }
        public virtual ICollection<tblSWATWAannualPrecip> tblSWATWAannualPrecips { get; set; }
        public virtual ICollection<tblSWATWAclimateChange> tblSWATWAclimateChanges { get; set; }
    }
}
