//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATBackgroundinfo
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> ClimateID { get; set; }
        public Nullable<int> SoilID { get; set; }
        public Nullable<int> EcoregionID { get; set; }
        public Nullable<int> WatershedID { get; set; }
        public Nullable<int> AribityID { get; set; }
        public Nullable<int> UrbanDistanceID { get; set; }
        public Nullable<long> Population { get; set; }
        public Nullable<int> numHouseholds { get; set; }
        public Nullable<int> numChildren { get; set; }
        public Nullable<double> PeoplePerHH { get; set; }
        public Nullable<int> isEconAg { get; set; }
        public Nullable<int> isEconLs { get; set; }
        public Nullable<int> isEconDev { get; set; }
        public Nullable<int> isEconPris { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> AreaForest { get; set; }
        public Nullable<double> AreaAg { get; set; }
        public Nullable<double> AreaInf { get; set; }
        public Nullable<double> AreaSw { get; set; }
        public Nullable<double> AreaWet { get; set; }
        public Nullable<double> AreaNat { get; set; }
        public Nullable<int> AreaProtID { get; set; }
        public Nullable<int> AreaBmID { get; set; }
        public Nullable<int> PriorQuality { get; set; }
        public Nullable<int> PriorQuan { get; set; }
        public Nullable<int> PriorSeasonal { get; set; }
        public Nullable<int> PriorPolitics { get; set; }
        public Nullable<int> PriorHealth { get; set; }
        public Nullable<int> PriorFinances { get; set; }
        public Nullable<int> PriorAccessible { get; set; }
        public Nullable<int> PriorEquity { get; set; }
    
        public virtual lkpBiome lkpBiome { get; set; }
        public virtual lkpClimateClassification lkpClimateClassification { get; set; }
        public virtual lkpSoil lkpSoil { get; set; }
        public virtual lkpSWATareaProtLU lkpSWATareaProtLU { get; set; }
        public virtual lkpSWATmapAridity lkpSWATmapAridity { get; set; }
        public virtual lkpSWATurbanDistanceLU lkpSWATurbanDistanceLU { get; set; }
        public virtual lkpSWATWatershedsLU lkpSWATWatershedsLU { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
