//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATCCgender
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> gRole1 { get; set; }
        public Nullable<int> gRole2 { get; set; }
        public Nullable<int> gRole3 { get; set; }
        public Nullable<int> gRole4 { get; set; }
        public Nullable<int> gRole5 { get; set; }
        public Nullable<int> gRole6 { get; set; }
        public Nullable<double> gRoleWomen { get; set; }
        public Nullable<int> gWomenEngage { get; set; }
        public Nullable<double> gWomenRep { get; set; }
    
        public virtual lkpSWATgenderLU lkpSWATgenderLU { get; set; }
        public virtual lkpSWATgenderLU lkpSWATgenderLU1 { get; set; }
        public virtual lkpSWATgenderLU lkpSWATgenderLU2 { get; set; }
        public virtual lkpSWATgenderLU lkpSWATgenderLU3 { get; set; }
        public virtual lkpSWATgenderLU lkpSWATgenderLU4 { get; set; }
        public virtual lkpSWATgenderLU lkpSWATgenderLU5 { get; set; }
        public virtual lkpSWATgWomenEngagedLU lkpSWATgWomenEngagedLU { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
