//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATCCschool
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<double> schoolAttend { get; set; }
        public bool schoolInstitution1 { get; set; }
        public bool schoolInstitution2 { get; set; }
        public bool schoolInstitution3 { get; set; }
        public bool schoolInstitution4 { get; set; }
        public Nullable<int> schoolHHAccess { get; set; }
    
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
