//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATLocation
    {
        public tblSWATLocation()
        {
            this.tblSWATSurveys = new HashSet<tblSWATSurvey>();
        }
    
        public int ID { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public int countryID { get; set; }
        public string name { get; set; }
        public int regionID { get; set; }
        public int subnationalID { get; set; }
    
        public virtual lkpCountry lkpCountry { get; set; }
        public virtual lkpRegion lkpRegion { get; set; }
        public virtual lkpSubnational lkpSubnational { get; set; }
        public virtual ICollection<tblSWATSurvey> tblSWATSurveys { get; set; }
    }
}
