//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATVisualGroup
    {
        public tblSWATVisualGroup()
        {
            this.tblSWATVisualGrpScoreMaps = new HashSet<tblSWATVisualGrpScoreMap>();
        }
    
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblSWATVisualGrpScoreMap> tblSWATVisualGrpScoreMaps { get; set; }
    }
}
