//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATScore
    {
        public tblSWATScore()
        {
            this.tblSWATVisualGrpScoreMaps = new HashSet<tblSWATVisualGrpScoreMap>();
        }
    
        public long ID { get; set; }
        public int SurveyID { get; set; }
        public int VariableID { get; set; }
        public Nullable<double> Value { get; set; }
        public string VarName { get; set; }
        public string Description { get; set; }
    
        public virtual lkpSWATScoreVarsLU lkpSWATScoreVarsLU { get; set; }
        public virtual ICollection<tblSWATVisualGrpScoreMap> tblSWATVisualGrpScoreMaps { get; set; }
    }
}
