//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATCCsocial
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> socHelp { get; set; }
        public Nullable<int> socClique { get; set; }
        public Nullable<int> socCBO { get; set; }
        public Nullable<double> socAttend { get; set; }
    
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU { get; set; }
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU1 { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
        public virtual lkpSWATsocCBOLU lkpSWATsocCBOLU { get; set; }
    }
}
