//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATSFsanitation
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> toiletsAll { get; set; }
        public Nullable<double> toiletHome { get; set; }
        public Nullable<double> toiletYard { get; set; }
        public Nullable<double> toilet100 { get; set; }
        public Nullable<double> toilet500 { get; set; }
        public Nullable<double> toiletFar { get; set; }
    
        public virtual lkpSWATtoiletsAllLU lkpSWATtoiletsAllLU { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
