//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATSFseptic
    {
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> septicToilets { get; set; }
        public Nullable<double> septicUnderstand { get; set; }
        public Nullable<double> septicDistance { get; set; }
        public Nullable<double> septicPlug { get; set; }
        public Nullable<double> septicPumped { get; set; }
        public Nullable<double> septicTrash { get; set; }
        public Nullable<double> septicChemicals { get; set; }
        public Nullable<int> septicChemAvail { get; set; }
        public Nullable<int> septicPumpAvail { get; set; }
        public Nullable<int> septicPubClean { get; set; }
        public bool septicPubAccessGroup1 { get; set; }
        public bool septicPubAccessGroup2 { get; set; }
        public bool septicPubAccessGroup3 { get; set; }
        public Nullable<int> septicfeesCharged { get; set; }
        public Nullable<int> septicFeesLimitAccess { get; set; }
        public Nullable<int> septicFeesEnsureClean { get; set; }
        public Nullable<int> hhSepticClean { get; set; }
    
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU { get; set; }
        public virtual lkpSWAT5rankLU lkpSWAT5rankLU1 { get; set; }
        public virtual lkpSWAThhCleanLU lkpSWAThhCleanLU { get; set; }
        public virtual lkpSWATpubCleanLU lkpSWATpubCleanLU { get; set; }
        public virtual lkpSWATYesNoLU lkpSWATYesNoLU { get; set; }
        public virtual lkpSWATYesNoLU lkpSWATYesNoLU1 { get; set; }
        public virtual lkpSWATYesNoLU lkpSWATYesNoLU2 { get; set; }
        public virtual tblSWATSurvey tblSWATSurvey { get; set; }
    }
}
