//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSWATWPquality
    {
        public long ID { get; set; }
        public long wpID { get; set; }
        public Nullable<int> qualTreated { get; set; }
        public Nullable<int> userTreated { get; set; }
        public Nullable<int> userTreatmentMethod { get; set; }
        public Nullable<int> faecalPathogens { get; set; }
        public Nullable<int> waterTaste { get; set; }
        public Nullable<int> waterOdour { get; set; }
        public Nullable<int> waterTurbidity { get; set; }
    
        public virtual lkpSWATfaecalPathogensLU lkpSWATfaecalPathogensLU { get; set; }
        public virtual lkpSWATqualTreatedLU lkpSWATqualTreatedLU { get; set; }
        public virtual lkpSWATuserTreatedLU lkpSWATuserTreatedLU { get; set; }
        public virtual lkpSWATuserTreatmentMethodLU lkpSWATuserTreatmentMethodLU { get; set; }
        public virtual lkpSWATwaterTasteOdourLU lkpSWATwaterTasteOdourLU { get; set; }
        public virtual lkpSWATwaterTasteOdourLU lkpSWATwaterTasteOdourLU1 { get; set; }
        public virtual lkpSWATwaterTurbidityLU lkpSWATwaterTurbidityLU { get; set; }
        public virtual tblSWATWPoverview tblSWATWPoverview { get; set; }
    }
}
